### ISSUE TITLE
Log When adding invalid ID

### ISSUE THREAD

**Issue by rgeorgi** [goodmami/xigt#17]
It seems that the "algnexpr_re" requires ids to begin with a letter, but this is not checked when elements are added, resulting in cases where the xml may look well-formatted, but the alignment resolution expressions do not function.

Repro:

### 
`<tier id="_e18c11e463694b21b8ae182a7da20f8c" type="translation-words" segmentation="r">`<BR>
    `<item id="_858f369b26e7408687e27132b5f1845d" segmentation="_0b86bfeeb5264dca9fdfe78eb9a74458[24:31]"/>`<BR>
`</tier>`

and the targeted item is:

###
`<tier id="r" type="odin" state="raw">`
       `<item id="_0b86bfeeb5264dca9fdfe78eb9a74458" tag="T+DB">            'I read her article.'                     'I read one of her articles.'</item>`
`</tier>`

**Comment by goodmami** [comment]
Ok, you're right there should be some validation when adding new items.

BTW: It looks like I followed the HTML ID format, which requires a letter as the first character. I should probably use the XML standard, which uses the Name production (which would allow underscores as the first character, among some other things).

http://www.w3.org/TR/REC-xml/#NT-Name
http://stackoverflow.com/questions/1077084/what-characters-are-allowed-in-dom-ids

**Comment by goodmami** [comment]
This will be resolved when it's merged to master, but note that I didn't change the form of IDs. Initial underscores are still invalid, but now a ValueError is thrown if you try to use an invalid Id.
