### ISSUE TITLE
Missing Imports in metadata.py

### ISSUE THREAD

**Issue by rgeorgi** [goodmami/xigt#22]
Looks like in moving metadata to its own module, a few imports got missed.

Add:
```import warnings```
```from xigt.errors import XigtError```

And looks like ```_has_parent``` is also missing from ```mixins```?

**Comment by goodmami** [comment]
Yes, you're right. I'm surprised Python didn't warn me, but then again those code paths are not explored by my unittests. I will add the imports.

Thanks!

**Comment by goodmami** [comment]
Resolved by fb1c98e03a03aa95cbeb36ffc5727fb9c65c1286
