### ISSUE TITLE
Minor Issue with Meta XML Rendering

### ISSUE THREAD

**Issue by rgeorgi** [goodmami/xigt#23]
When serializing metadata in XML, using the ```text=``` attribute on the Meta item, it seems that the meta items get rendered like:

```xml
    <metadata type="xigt-meta">
      <meta type="data-source">intent
      </meta>
      <meta type="data-method">mgiza
      </meta>
    </metadata>
```
With newlines before the close tag. It would be nice instead to have something like:

```xml
    <metadata type="xigt-meta">
      <meta type="data-source">intent</meta>
      <meta type="data-method">mgiza</meta>
    </metadata>
```

**Comment by goodmami** [comment]
Yes this is currently not ideal because I don't know when the text might have contentful whitespace. I can probably not output newlines if there's only text and no children.
